---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api3
spec:
  selector:
    matchLabels:
      app: api3
  template:
    metadata:
      labels:
        app: api3
    spec:
      containers:
      - name: api3
        image: api3
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api3
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: api3
