// Generated by delombok at Thu May 08 09:08:45 EDT 2025
// package pets;
public class Pet {
   public String Name;

   @Override
   public String toString() {
      return String.format("%s", Name);
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public String getName() {
      return this.Name;
   }

   @java.lang.SuppressWarnings("all")
   @lombok.Generated
   public void setName(final String Name) {
      this.Name = Name;
   }
}
