version: '3.9'

services:
  frontend:
    image: frontend
    build: 
      context: ./src/frontend
      dockerfile: Dockerfile
    environment:
      - backendURL=http://backend:8081
    ports:
      - 8080:80
    depends_on:
      - backend

  backend:
    image: publicapi
    build: 
      context: ./src/publicAPI
      dockerfile: Dockerfile
    environment:
      - api1=http://api1 # these are all using port 80
      - api2=http://api2
      - api3=http://api3
      - auth=http://auth
    ports:
      - 8081:80

  auth:
    image: auth
    build: 
      context: ./src/auth
      dockerfile: Dockerfile

  api1:
    image: api1
    build: 
      context: ./src/privateAPI1
      dockerfile: Dockerfile

  api2:
    image: api2
    build: 
      context: ./src/privateAPI2
      dockerfile: Dockerfile

  api3:
    image: api3
    build: 
      context: ./src/privateAPI3
      dockerfile: Dockerfile

