/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import io.upwake.oneof.OneOf2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    private static OneOf2<String, MyError> doStuff(Boolean ans) {
        if (ans) {
            return OneOf2.of1("Everybodies happy");
        } else {
            return OneOf2.of2(new MyError("something's broken"));
        }
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        System.out.println(doStuff(true)._1());
        System.err.println(doStuff(false)._2().getMessage());
    }
}

class MyError {
    private final String _message;

    public MyError(String message) {
        _message = message;
    }

    public String getMessage() {
        return _message;
    }
}
