apiVersion: apps/v1
kind: Deployment
metadata:
  name: formulaone
spec:
  selector:
    matchLabels:
      app: formulaone
  template:
    metadata:
      labels:
        app: formulaone
        app.kubernetes.io/name: formulaone
    spec:
      containers:
      - name: formulaone
        image: formulaone
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 80
            name: http-web-api
        env:
          - name: ASPNETCORE_URLS
            value: http://+:80
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
spec:
  selector:
    app.kubernetes.io/name: formulaone
  ports:
    - name: "8085"
      protocol: TCP
      port: 8085
      targetPort: 80
  type: LoadBalancer
