apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.29.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: backend
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.29.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/async-multicall-default: "true"
        io.kompose.service: backend
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://*:80
            - name: api1
              value: http://api1
            - name: api2
              value: http://api2
            - name: api3
              value: http://api3
            - name: auth
              value: http://auth
          image: publicapi
          name: backend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              # hostPort: 8081
              # protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
