
all: hsi streamlyne suitable

hsi:
	go run ./cmd/hsi


streamlyne:
	go run ./cmd/streamlyne

streamlyneBuild:
	go build -o ./bin/streamlyne ./cmd/streamlyne

suitable:
	go run ./cmd/suitable

suitableBuild:
	go build -o ./bin/suitable ./cmd/suitable
