
# this uses ./ at the front because you need the go compiler to see all the files in the web folder
# and not just the main.go as I would normally just do go run cmd/web/main.go

run: 
	go run ./cmd/web

db_init:
	go run ./cmd/db_init_cli