

serial:
	go run cmd/serial/main.go

basic:
	go run cmd/basic/main.go

channel:
	go run cmd/channel/main.go

buffered_channels:
	go run cmd/buffered_channels/main.go

iteration:
	go run cmd/ch_iteration/main.go

select:
	go run cmd/ch_select/main.go

waitgroup:
	go run cmd/waitgroup/main.go

mutex:
	go run cmd/mutex/main.go

once:
	go run cmd/once/main.go

pool:
	go run cmd/pool/main.go

signal:
	go run cmd/signal_broadcast/main.go

map:
	go run cmd/map/main.go

atomic:
	go run cmd/atomic/main.go
